services:
  web-gateway:
    image: javaspark/web-gateway
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  inventory-service:
    image: javaspark/inventory-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  account-service:
    image: javaspark/account-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  order-service:
    image: javaspark/order-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  postgres:
    image: javaspark/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "spark-postgres-volume:/var/lib/postgresql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  rabbitmq:
    image: rabbitmq:4
    hostname: "rmq"
    volumes:
      - "spark-rabbitmq-volume:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  spark-postgres-volume:
  spark-rabbitmq-volume: